PPiing/frontend

.dockerignore
.github/workflows/cicd.yaml
Dockerfile

- FE 파트의 CI/CD 이슈 사항이였던 Build 에러 관련 사항을 수정하였습니다.
- 수정내용
1. src 파일 상 예시로 잡아두었던 폴더구조 전체 삭제 
- vite.config 상에 적혀있는 포트와 호스트는 이미 고쳐져 있었습니다! (@joohongpark @HyeonsikBae 에게 감사를!)
- CI / CD의 빌드에러를 수정하기 위해, 내용이 없는 src 파일을 소거하였습니다.

:bug: 05/03_IP_Build_Error_Fixed(src_file_removed) 관련

---

.github/workflows/cicd.yaml

- GitHub Actions 스크립트에 빌드 테스트도 추가하였습니다.
- #7

🔧 #7 add build test @ CI

---

src/App.tsx
src/container/contents.tsx
src/container/navCommunity.tsx
src/container/navMenu.tsx
src/view/home.tsx

- 홈 뷰 샘플 작업
- Menu Nav, Community Nav, Contents 구성을 위한 샘플 뷰 작성

:sparkles: #10 add Home sample view

---

package-lock.json
src/component/nav/navAlam.tsx
src/component/nav/navInviteZone.tsx
src/component/nav/navSearch.tsx
src/container/contentChat.tsx
src/container/contentGame.tsx
src/container/contentProfile.tsx
src/container/navCommunity.tsx

- 각 컴포넌트트 내에 간략한 statement /  interface 명기 
(+ 모두 한 자리에서 회의하면서 naive 하게 적어서, 다소 두서가 없습니다만..! 곧 정리하여 명기하겠습니다! )
- 각 컴포넌트가 보여지는 view 중심으로 만들어지고 있어요. 각 컴포넌트는 유기적으로 데이터를 주고받게 될 텐데, 이에 대한 깊은 고려와 기획이 부족하다고 생각됩니다. 이를 명료히 하기 위해, 각 container 내에서 Statement / Interface 를 명시하는 작업을 진행했습니다.

✨ component's Statement / Interface 확정하기 #26

---

index.html
package-lock.json
package.json
src/App.tsx
src/component/neon/NeonButton.tsx
src/container/contentChat.tsx
src/container/contentGame.tsx
src/container/contentHome.tsx
src/container/contentProfile.tsx
src/container/contentWatch.tsx
src/container/navMenu.tsx
src/theme/theme.tsx
src/view/viewChat.tsx
src/view/viewGame.tsx
src/view/viewHome.tsx
src/view/viewProfile.tsx
src/view/viewWatch.tsx

- 각 버튼에 페이지 네이게이션 기능을 구현하여 넣어두었어요. 이제 nav Button으로 각 페이지 이동이 가능합니다.
contents 컨테이너 중앙에, 햔재 페이지를 알수 있도록 marking 하기 위해 텍스트가 추가되어있으나, 편히 제거하셔도 무방합니다 :)
- 각 버튼으로 페이지 네비게이팅을 할 수 있게 구현해야, 게임이나 채팅 등 별도 기능들을 구현할수 있을 거라 생각했습니다! 3D 게임 제작을 위해 라우팅 처리 먼저 해두었어요!

:art: 06/02_make_button_navigation_for_routh_pages #28

---

src/theme/theme.tsx

:bug: #35 Fix scroll bug Edit theme.tsx

---

package-lock.json
src/container/contentChat.tsx
src/container/contentGame.tsx
src/container/contentHome.tsx
src/container/contentProfile.tsx
src/container/contentTemplate.tsx
src/container/contentWatch.tsx
src/theme/theme.tsx
src/view/viewChat.tsx
src/view/viewGame.tsx
src/view/viewHome.tsx
src/view/viewProfile.tsx
src/view/viewTemplate.tsx
src/view/viewWatch.tsx

- #33 대로 template 적용하였습니다!
- 내용을 적어주세요.

:🚧 22/05/18 #33 template for container, view

---

src/App.tsx
src/container/contentGame.tsx
src/view/viewLogin.tsx

- NavMenu 버튼 사이즈가 바뀜에 따라, 3D Game 화면의 Border 프레임을 다시 작업하여 올립니다!
- 화면의 전체 content 사이즈가 바뀌어서, 보이는 Frame 부분을 재작업 했어요.

:building_construction: 06/08_reconstructing_3DGame_Border_Frame #44

---

package-lock.json
package.json
src/container/contentChat.tsx
src/feat/chat/socket.ts

- 채팅 기능 구현을 위한 임시 로그인 구현
- socket 연결 구현
- 현재 URL이 localhost로 되어 있어 배포되어 있는 서버에서 기능 검증 필요
- 로그인 기능 미구현

#51 feat: temp login with socket.io

---

src/container/navCommunity.tsx
src/view/viewTemplate.tsx

- viewTemplate 오타 수정 및 어거지로 버그 고쳐둔 코드 삭제.
- navCommunity style 코드 수정.
- Right nav height bug fix.

:bug: #62 Right nav height bug fixed

---

src/component/rootControl.tsx
src/feat/nav/request.ts

- redirect, auth 관련 코드 수정
- redirect CD 테스트

:bug: #66 Fix redirect

---

src/component/nav/navAlam.tsx
src/component/rootControl.tsx
src/redux/slices/auth.ts
src/view/viewTemplate.tsx

- redirection 문제 해결을 위한 auth redux data 로그 추가.
- redirection 문제 해결.

:bug: #66 Add log for fix bug

---

src/component/nav/navAlam.tsx
src/component/rootControl.tsx
src/feat/nav/request.ts
src/redux/slices/auth.ts
src/view/viewLogin.tsx
src/view/viewTemplate.tsx

- nav feat 관련하여 useEffect 제거하고 종속성 제거하여 redux dispatch시 무한루프 방지.
- nav feat
- 리눅스가 로컬에서 백을 못돌려서 잦은 PR 양해 부탁드려요.. 테스트하려면 CD 가야함ㅜㅠ.

:hammer: #66 Feat on going for profile on nav

---

src/network/api/axios.custom.ts
src/network/api/axios.instance.ts

- set up axios
- axios instance 생성
- axios instance에 기본 세팅 설정
- baseURL
- interceptors
- timeout 5000ms
- axios에 전역 설정 적용
- axios에 200번대 외의 http response를 받는 경우에 대한 일괄 에러 처리 적용

feat: set up axios

---

src/component/chat/chatFindRoom.tsx
src/container/contentChat.tsx
src/interface/chat/roomlist.interface.ts
src/network/api/axios.custom.ts
yarn.lock

#83 feat: chatroom search

---

src/component/nav/navFriendZone.tsx
src/network/api/axios.custom.ts

- 디버깅 위한 로그 추가
- JSX insert key 값 추가
- 버그 수정.
- 통신 디버그.

:hammer: #66 Add log for debug and insert key

---

src/component/nav/navFriendZone.tsx
src/network/api/axios.custom.ts

- axios return add.
- Fix axios mistake about nav search feature.

:hammer: #66 Fix code about search axios.

---

src/container/contentProfile.tsx

Reverts PPiing/frontend#101 죄쏭하빈다

Revert "testing"

---

src/container/contentProfile.tsx
src/view/viewTemplate.tsx

:fire: #47 game history, user template

---

src/component/chat/chatCreateRoom.tsx
src/component/chat/chatFindRoom.tsx
src/container/contentChat.tsx

chore: chat 관련 주석 추가

---

src/container/contentProfile.tsx
src/feat/profile/request.ts
src/theme/theme.tsx

🚧 #47 프로필 페이지 하찮은 디자인 수정

---

src/container/contentGame.tsx
src/container/contentGameRule.tsx

- 대기화면을 만들었습니다. rule Selection을 처리하고 나서 소켓으로 통신하는 부분은 벡엔드와 연결 후 빌드할 예정입니다.
- 일단 보이는 부분만 빌드를 해놓은 상황으로 봐주시면 될 듯!

:construction: 07/11_Add_Rotating_model_for_Wating_page #110

---

src/component/modal/content/modalNavFriendBox.tsx
src/component/nav/navAlam.tsx
src/component/nav/navFriendBox.tsx
src/component/nav/navSearchResultBox.tsx

- nav search feature에서 변경된 API 명세를 맞추지 못한 것을 수정.
- 베이스 URL에 따른 nav profile img 깨짐 문제를 해결하기 위해 절대경로로 이미지를 받아오도록 함.
- nav search feature 정상화.

:hammer: #66 Nav search feat. Apply API change.

---

src/component/modal/content/modalNavFriendBox.tsx
src/container/contentProfile.tsx
yarn.lock

🚧 #118 #119 profile modal 개선 : Button Link 이동 시 modal 안 꺼지는 현상

---

src/container/contentProfile.tsx

- profile - nickname, twoFactor, Image에 대해 axios patch 보내는 내용을 추가하였습니다.
- **푸쓰푸쓰팍**님과 이미지 업로드 기능을 내일 하겠습니다. 굿
- 내용을 적어주세요.

🚧 #118 #119 profile modal 개선 : axios patch 연결

---

src/container/contentGame.tsx
src/container/contentGameRule.tsx
src/redux/slices/gameRule.ts

- 3D 렌더 모델을 추가하고, 그 외 자잘한 로직들을 수정했습니다. 소켓 연결을 비롯한 추가작업을 수행 중입니다.

:zap: 07/13_Build_some_feat #110

---

src/container/contentGameRule.tsx

- 3D 모델 이미지의 file Path 를 수정합니다!

:bug: 07/13_Fix_3D_file_path #110

---

src/component/chat/chatCreateRoom.tsx
src/component/chat/chatFindRoom.tsx
src/component/chat/chatRoom.tsx
src/view/viewTemplate.tsx

- Fixed Chat's Duplicated Border
- Made default modal form for Chat

🚧 chat : remove duplicated border #115, chat modal 붙임

---

src/container/contentProfile.tsx

🚧 profile error test

---

src/container/contentProfile.tsx

Bugs/alot 

---

src/component/chat/chatRoom.tsx
src/component/modal/content/modalChatExit.tsx
src/container/contentProfile.tsx
yarn.lock

🚧 profile file upload test

---

src/component/chat/chatRoom.tsx
src/component/modal/content/modalChatUserList.tsx
src/component/modal/content/modalChatUserListBox.tsx
src/container/contentProfile.tsx

🚧 many things (chat, profile, modal, ...)

---

src/network/api/axios.custom.ts

- arrow function 규칙에 맞춰 axios 요청 성공 시, 임의의 null 반환
- arrow function 규칙에 맞춰 axios 요청 실패 시, error 반환
- error

fix: axios error

---

src/component/chat/chatRoom.tsx
src/component/modal/content/modalChatUserList.tsx
src/component/modal/content/modalChatUserListBox.tsx

- User List 조회 후 ModalContent에 보내기
- UseEffect를 통한 get 무한요청 없애기
- 내용을 적어주세요.

🚧 Chatting: User List 조회 후 ModalContent에 보내기, UseEffect를 통한 get 무한요청 없애기

---

src/container/contentProfile.tsx

- 이미지, 닉네임 변경 이벤트에 대해 보완 및 수정을 하였습니다.
- 컴포넌트가 보여지는 값을 바꿔야 하는 경우 (이미지 URI, 닉네임)에 대해선 리액트 훅을 사용했습니다.
- #160

이미지, 닉네임 변경 이벤트 보완 및 수정

---

src/component/modal/content/modalNavFriendBox.tsx

- profile modal에 axios와 response 연결 작업을 완료하였습니닷
- 내용을 적어주세요.

🚧 modal: profile modal..

---

src/component/modal/content/modalNavFriendBox.tsx
src/component/nav/navFriendBox.tsx
src/view/viewTemplate.tsx

- pofile modal bug fixed,
- viewtemplate - replace solved

🚧 profile modal bug fixed, viewtemplate - replace solved

---

src/container/contentGameRule.tsx

- 모델의 file Path를 수정하여 다시 올립니다!

:art: 07/20_Fix_3Dmodel_Path #110

---

src/container/contentGameRule.tsx

:art: 07/20_ReFix_3Dmodel_Path #110

---

src/container/contentGameRule.tsx

:art: 07/20_ReFix_3Dmodel_Path_in_lower_case #110

---

src/component/chat/chatRoom.tsx
src/theme/theme.tsx

- chat의 기존 모달을 MUI로 대체하는 작업 진행중입니다.

🚧 chat modal

---

src/component/chat/chatRoom.tsx
src/container/contentChat.tsx
src/interface/recvMessage.interface.ts
src/network/api/axios.custom.ts

feat: recvMsg

---

src/component/modal/content/modalChatUserListBox.tsx

🚧 MUI Modal content

---

src/component/chat/chatCreateRoom.tsx
src/component/chat/chatFindRoom.tsx
src/container/contentChat.tsx
src/feat/chat/socket.ts
src/feat/game/socket.ts
src/feat/profile/request.ts
src/network/api/axios.custom.ts
src/network/api/socket.ts
src/redux/slices/joinedChatRoomList.ts

- 백앤드의 채팅 관련 기능 (세션 도입, 실DB 연동)이 변경됨에 따라 프론트엔드에 대해 일부 기능을 변경하였습니다.
- 채팅 접속시 자동 연결
- 미사용 코드 제거
- uri에서 by 받는 부분 제거
- 후속으로 채팅 관련 기능들을 적용하는 작업을 프론트앤드 분들과 소통하며 지속적으로 진행해야 할 듯 합니다.
- #179

채팅 소켓연결 개선

---

src/component/modal/content/modalNavFriendBox.tsx

🚧 logout feat

---

src/component/modal/content/modalNavFriendBox.tsx
src/component/nav/navAlam.tsx
src/theme/theme.tsx

- navFriendBox : 안 쓰는 모달 코드 삭제
- NavAlarm : Div-Img 형태의 이중 구조를 Img로만 고쳤습니다
- theme: ```aspectRatio: 1```을 통해 1대1 비율을 유지하도록 설정하였습니다.

🚧 :183 프사가 동그랗지 않은 현상 해결

---

src/container/contentChat.tsx
src/redux/slices/joinedChatRoomList.ts

- render joined room with sample data
- to verify function

feat: edit type for socket event(chat:init)

---

src/component/chat/chatRoom.tsx
src/container/contentChat.tsx
src/redux/slices/joinedChatRoomList.ts
yarn.lock

- redux에 joinedRoomList저장 시, 중복이 없는 경우만 저장
- 같은 룸이 여러번 렌더되는 버그

fix: joinedRoomList

---

src/component/chat/chatRoom.tsx

- print receive message
- test socket event

feat: checkRecvMsg

---

src/container/contentProfile.tsx

- achiv img 링크가 잘못되서 안 불러와지던 현상 해결했습니다
- profile css 개선했습니다

:sparkles: achiv img 링크가 잘못되서 안 불러와지던 현상 해결, css 개선

---

src/component/button/ToolTip.css
src/component/chat/chatRoom.tsx
src/component/modal/modalChatUserList.tsx
src/component/modal/modalChatUserListBox.tsx
src/component/modal/modalCheck.tsx
src/container/contentProfile.tsx

- Check Modal
- ToolTip CSS
- ContentProfile Bug
- Chat User List Axios

:sparkles: Check Modal, ToolTip CSS, ContentProfile Bug, Chat User List Axios

---

src/component/modal/modalNavFriendBox.tsx
src/component/nav/navFriendZone.tsx

- User Modal Refactoring
- Nav Friend Zone Optional Chaning Added

:sparkles: User Modal Refactoring, Nav Friend Zone Optional Chaning Added

---

src/component/modal/modalChatSetting.tsx
src/network/api/axios.custom.ts

- user search invite 작업 완료했습니다
- 검색 시 리스트 안띄우고 바로 처리하도록 했습니다
- 대신 응답 메시지만 밑에 띄워주도록 처리했습니다
- 안되는 에러 상황은 다 처리한 것 같지만, 특수문자 검색 시 에러 뜨는 것이랑 신규유저 더미 넣어서 테스트까지 해봐야 합니당
- 이슈 만들어 놓겠습니다

:feature: user search and invite

---

src/component/modal/modalNavFriendBox.tsx
src/network/api/axios.custom.ts
yarn.lock

<p style="color: #000000">형유 보고있나</p>

:bug: profile modal bug

---

src/container/contentProfile.tsx
src/network/api/axios.custom.ts

:feature: nickname valid check

---

src/network/api/axios.custom.ts

- Alarm 관련 axios 함수에서 변경된 API 명세 적용.
- 명세 변경에 따른 업데이트.

:hammer: Alarm axios fixed.

---

src/App.tsx
src/container/contentTwoFactor.tsx
src/network/api/axios.custom.ts
src/view/viewRedirect.tsx

:feaeture: twofactor redirect

---

src/component/nav/navInviteBox.tsx

- Alarm confirm 명세에 맞춘 axios 인자 변경.
- 기능 정상화.

:hammer: Alarm confirm fixed.

---

src/component/chat/chatMessage.tsx
src/component/chat/chatRoom.tsx

- chatting render 완료하였습니다.
- 날짜가 임의로 8/15로 들어가있어서 변환 과정 필요합니다.
- 방 옮겼을 때/메시지 보냈을 때 다시 렌더하는 것, 메시지 보내는 기능, 방찾아서 들어가기, 방 생성 기능들이 남았습니다

⚡ chat render good (날짜 변환 필요)

---

src/component/modal/modalNavFriendBox.tsx
src/component/nav/navInviteBox.tsx
src/network/api/axios.custom.ts

- Game invite API 추가에 따른 기능 구현.
- 기존의 알림 리스트 관리 버그 수정. alarmSeq와 userSeq 혼용으로 인한 문제였음.
- 알림 리스트 관리 버그 수정.
- 기능 반영.

:hammer: Game invite feature and alarm fixed.

---

src/container/contentChat.tsx

- 채팅 룸 리스트 버그 해결을 위한 초기화 프로세스 추가.
- 버그 픽스.

:bug: #190 Joined chatroom list bug fixed.

---

src/container/contentChat.tsx

- 채팅방 리스트 디스플레이시 타입을 구분하지 않는 문제 해결을 위한 조건 분기 및 filter 사용.
- 버그 픽스.

:bug: #190 Chatroom list type bug fixed.

---

src/component/chat/chatMessage.tsx
src/component/chat/chatRoom.tsx
src/component/modal/modalNavFriendBox.tsx
src/network/api/axios.custom.ts

:sparkles: chatting list user modal

---

src/component/nav/navFriendZone.tsx
src/network/api/axios.custom.ts

- 친구 목록 갱신 및 상태 갱신 소켓 수정.
- 알림 리스트 삭제와 관련하여 디버그 로그 추가.
- 기능 구현.
- 디버그.

:hammer: Friendlist refresh socket fixed. Add some log for debug.

---

src/component/chat/chatRoom.tsx
src/component/modal/modalChatSetting.tsx
src/component/modal/modalNavFriendBox.tsx

- chatting room render 작업하던 중 생긴 dummy 작업들입니다. 임시로 올리겠습니다.
- 봉천에서 테스트하려구요

:sparkles: 수정 사항 들

---

src/component/nav/navFriendZone.tsx

- 없는 소켓 네임스페이스에 연결하면 백이 터지므로 해당 주석처리.
- 당장의 터짐 해결.

:bug: Socket issue fixed.

---

src/component/nav/navFriendZone.tsx

:bug: Socket issue temp fixed.

---

src/component/nav/navFriendZone.tsx
src/container/contentGame.tsx
src/container/contentGameRule.tsx
src/view/viewGame.tsx

- 백엔드 게임서버와의 위치 좌표값 연산비율 재조정
- 블루 사이드 / 레드 사이드의 네이밍 값, 득점 가산 로직 추가
- 그 외 마이너 업데이트 사항 추가

:zap: 08/11_Fix_Coordinate_Position_and_minor_fixs_added #213

---

src/container/contentGame.tsx
src/view/viewGame.tsx

:zap: 08/12_Add_ending_text_and_last_wording_effect #233

---

src/component/chat/chatMessage.tsx
src/component/chat/chatRoom.tsx

:infinity_loop:

---

src/component/chat/chatRoom.tsx

bongcheon test

---

src/redux/slices/choosableAlamList.ts

:bug: Alarm remove reducer fixed.

---

src/component/chat/chatRoom.tsx

히히 채팅지옥에 빠져라

---

src/network/api/axios.custom.ts

- 디버그 로그 삭제.
- 로그삭제를 빙자한 테스트 위한 CD 리스타트용.

:hammer: Log removed and CD restart.

---

src/network/api/axios.custom.ts

- 알림 수신시 프론트에서 해당 알람을 리스트에 두번 넣어버리는 문제 발견하여 수정.
- 버그 픽스.

:bug: Alarm overlap filter added.

---

src/network/api/axios.custom.ts

:bug: Alarm list overlap bug fix.

---

src/network/api/axios.custom.ts

:bug: Add log for debug.

---

src/network/api/axios.custom.ts

:bug: Add more debug log.

---

src/component/chat/chatMessage.tsx
src/component/chat/chatRoom.tsx
src/interface/recvMessage.interface.ts
src/main.tsx

:stric mode 뺴고 올림 ㅋㅋ

---

src/network/api/axios.custom.ts

- 리덕스 리스트에 알람 중복 삽입 코드 재코딩.
- 디버그.

:bug: Recode alarm overlap filter.

---

src/component/chat/chatRoom.tsx

amdksmaksd

---

src/component/chat/chatRoom.tsx

- 채팅방 옮길 시 재 렌더 확인
- 다른 채팅방이면 소켓 안 오게도 함

:sparkles: chatting list render

---

src/component/chat/chatCreateRoom.css
src/component/chat/chatCreateRoom.tsx

:sparkles: chat create room

---

src/component/chat/chatRoom.tsx
src/container/contentChat.tsx

:sparkles: chat yeah

---

src/component/chat/chatFindRoom.tsx
src/component/chat/chatRoom.tsx

- chat socket - location reload로 처리
- 테스트

:sparkles: chat join

---

src/component/chat/chatFindRoom.tsx
src/component/chat/chatRoom.tsx
src/component/modal/modalNavFriendBox.tsx

:sparkles: 채팅이 나는. 싫습니

---

src/component/modal/modalCheck.tsx
src/container/contentProfile.tsx
src/network/api/axios.custom.ts

난 트센을 부술거야git add *

---

src/container/contentGame.tsx
src/view/viewGame.tsx

- 게임 중 새로고침 시, 게임방으로 재접속하는 로직 설정
- 내용을 적어주세요.

:zap: 08/13_Fix_refresh_rejoin_Logic #233

---

src/container/contentGame.tsx
src/container/contentGameRule.tsx
src/redux/slices/gameRule.ts

- 게임 DeQ 가능하도록 버튼 작업
- WebGL 한글 폰트 작업에 맞게 크기와 위치값 수정

:zap: 08/13_Add_DeQ_logic_and_Fix_text_Sizing #233

---

src/container/contentGame.tsx
src/container/contentGameRule.tsx
src/feat/game/socket.ts
src/view/viewGame.tsx
vite.config.ts

- 중복된 socketManager 삭제
- vite config 파일 내 포트 설정 추가

:bug: fix: add port setting & remove duplicated socketManager #269

---

src/component/chat/ChatRoomMessageArea.tsx
src/component/chat/chatRoom.tsx
src/container/contentChat.tsx

- socket을 통해 메세지 받을 시, 해당 메세지 렌더
- chat

feat: render messages

---

src/container/contentChat.tsx

- contentChat 코드 내부 import Lint 오류 수정.
- 린트 오류 제거.
_쉬운 오류인데 왜 메인에 바로?_

:bug: Lint fixed.

---

src/component/chat/ChatInput.tsx

- 채팅에 한글 입력 시 이벤트가 2번 발생하던 에러 수정
- 내용을 적어주세요.

fix: input korean

---

src/container/contentGameRule.tsx
src/redux/slices/gameRule.ts

- isRank의 기본값을 변경하여, 기본 룰이  Rank 전인 것에 매칭하였습니다.
- 슬라이더의 default Value를 변경하여, 리덕스가 이전에 체크해두었던 룰의 값을 반영하도록 재설계했습니다.

:zap: 08/17_Fix_default_isRank_and_ruleSelector_defaultValue #233

---

src/container/contentProfile.tsx
src/network/api/axios.custom.ts

:sparkles: nickname change update

---

src/component/chat/ChatRoomHeaderInfo.tsx
src/component/modal/modalChatSetting.tsx
src/network/api/axios.custom.ts

- chat room setting view, axios finish

:feature: chat room setting

---

src/component/modal/modalNavFriendBox.tsx

- searchSeq를 잘못 만들어서 문제가 발생했었습니다.

:bug: bug fix

---

src/component/nav/navInviteZone.tsx
src/redux/slices/choosableAlamList.ts

:bug: 강제 새로고침 ^^ #293

---

src/component/modal/modalCheck.tsx
src/redux/slices/joinedChatRoomList.ts

:bug: room exit fix (backend fix needed)

---

src/network/api/axios.custom.ts

:sparkles: #297 function

---

src/component/chat/ChatRoomHeaderInfo.tsx
src/component/modal/modalChatUserList.tsx

- chatUserList Interface 고려 중
- 내용을 적어주세요.

temp: chatUserList

---

src/component/modal/modalChatUserList.tsx
src/network/api/axios.custom.ts

- interface 변경 및 추가 데이터 수집
- 내용을 적어주세요.

fix: chatUserList interface

---

src/component/nav/navInviteZone.tsx
src/container/contentGameRule.tsx
src/redux/slices/gameRule.ts
src/view/viewGame.tsx
yarn.lock

- game invite 의 로직 수정
- 초대를 수락할 시, 두 유저가 모두 인게임 화면으로 넘어가도록 수정 
- 추가적 수정이 조금 더 필요한 상황이므로, 내일 중 처리하겠습니다!
- 내용을 적어주세요.

⚡️ 08/18_Fix_gameInvite_redirect_logic #233

---

src/component/button/ToolTip.css
src/component/modal/modalChatUserList.tsx
src/component/modal/modalChatUserListBox.tsx

:sparkles: chat modal temp

---

src/component/nav/navAlam.tsx

:art: online color change

---

src/redux/slices/gameRule.ts
src/view/viewGame.tsx

GAME: reduser-blueuser

---

src/component/modal/ModalBanUserListBox.tsx
src/component/modal/modalChatUserList.tsx
src/network/api/axios.custom.ts

feat: unban

---

src/network/api/axios.custom.ts

:hammer: Block filter fixed.

---

src/component/modal/modalNavFriendBox.tsx
src/component/nav/navInviteZone.tsx
src/container/contentGame.tsx
src/container/contentGameRule.tsx
src/view/viewGame.tsx

- 게임초대 로직 작성하였어요!
- 모달 부분과 nav 부분 전체에 ready 소켓을 달아, 신호를 감지할 수 있도록 수정했어요.
- 초대로 생성된 게임도 유저네임과 스코어 등등을 제대로 갱신할 수 있게 수정했어요.
- 인게임 상태를 감지하는 isInGame 변수를 제대로 컨트롤 할수 있게 수정했어요.

:zap: 08/17_Build_Game_Invite_Logic #233

---

src/container/contentGame.tsx
src/container/contentGameRule.tsx
src/redux/slices/gameRule.ts

- 두 유저가 같이 게임 밖으로 나갔을 시, 스코어 렌더링 변경값 저장 로직을 작성했어요.

:zap: 08/19_Fix_Score_Store_Logic #233

---

src/component/chat/ChatRoomMessageArea.tsx
src/component/chat/chatRoom.tsx
src/container/contentProfile.tsx
src/container/contentTwoFactor.tsx
yarn.lock

chatting dm block, profile key not fixed
